const Map<String, String> enUS = {
  'hello': 'Hello',
  'welcome': 'Welcome',
  'Home':'Home',
  'Quick Action':'Quick Action',
  'Select Language':'Select Language',
  'Recent Purchase Order':'Recent Purchase Order',
  'Recent Sale Order':'Recent Sale Order',
  'View All':'View All',
  'Login':'Login',
  'Enter username': 'Enter username',
  'Enter password': 'Enter password',
  'Good Morning 👋': 'Good Morning 👋',
  'Good Afternoon': 'Good Afternoon',
  'Good Evening': 'Good Evening',
  'Good Night': 'Good Night',
  'Welcome Back': 'Welcome Back',
  'Sale':'Sale',
  'Category':'Category',
  'Product':'Product',
  'Supplier':'Supplier',
  'Qty':'Qty',
  'Price':'Price',
  'Date':'Date',
  'Purchase':'Purchase',
  'Category Management':'Category Management',
  'Customer':'Customer',
  'Audit Logs':'Audit Logs',
  'Stock Adjustment': 'Stock Adjustment',
  'Stock Transfer': 'Stock Transfer',
  'Warehouse': 'Warehouse',
  'Sale List': 'Sale List',
  'Sale Payment': 'Sale Payment',
  'Role': 'Role',
  'User': 'User',
  'Product & Category Management': 'Product & Category Management',
  'Search Category':'Search Category',
  'Add Category':'Add Category',
  'Edit Category':'Edit Category',
  'Category Name': 'Category Name',
  'Icon': 'Icon',
  'Description':'Description',
  'Enter Category Name': 'Enter Category Name',
  'Enter Description': 'Enter Description',
  'Enter Icon':'Enter Icon',
  'Save':'Save',
  'Delete':'Delete',
  'Edit':'Edit',
  'Search Product':'Search Product',
  'Add Product':'Add Product',
  'Pick Image':'Pick Image',
  'Enter Category':'Enter Category',
  'Select Category':'Select Category',
  'Product Name': 'Product Name',
  'Enter Product Name': 'Enter Product Name',
  'Select Supplier':'Select Supplier',
  'Barcode':'Barcode',
  'Enter Barcode':'Enter Barcode',
  'Cost Price':'Cost Price',
  'Enter Cost Price':'Enter Cost Price',
  'Sale Price': 'Sale Price',
  'Enter Sale Price':'Enter Sale Price',
  'Quantity':'Quantity',
  'Enter Quantity':'Enter Quantity',
  'Unit':'Unit',
  'Select Unit':'Select Unit',
  'Product Detail':'Product Detail',
  'Edit Product':'Edit Product',
  'Total Purchases':'Total Purchases',
  'Purchases':'Purchases',
  'Search Purchases...':'Search Purchases...',
  'Search Suppliers':'Search Suppliers',
  'Suppliers':'Suppliers',
  'Add Supplier':'Add Supplier',
  'Supplier Name':'Supplier Name',
  'Enter Supplier Name':'Enter Supplier Name',
  'Phone Number':'Phone Number',
  'Enter Phone Number':'Enter Phone Number',
  'Email':'Email',
  'Enter Email':'Enter Email',
  'Map': 'Map',
  'Enter Map': 'Enter Map',
  'Address': 'Address',
  'Enter Address': 'Enter Address',
  'Status': 'Status',
  'No supplier data found':'No supplier data founds',
  'Supplier Detail':'Supplier Detail',
  'Supplier Information': 'Supplier Information',
  'Created': 'Created',
  'Edit Supplier':'Edit Supplier',
  'Search Customers by name or ID':'Search Customers by name or ID',
  'Total Customers':'Total Customers',
  'Active Customers':'Active Customers',
  'Inactive Customers':'Inactive Customers',
  'Customer Name':'Customer Name',
  'Add Customer':'Add Customer',
  'Enter Customer Name':'Enter Customer Name',
  'Edit Customer':'Edit Customer',
  'Search Stock Adjustment':'Search Stock Adjustment',
  'Select Product':'Select Product',
  'Select Warehouse':'Select Warehouse',
  'Add Stock Adjustment':'Add Stock Adjustment',
  'Adjustment Type': 'Adjustment Type',
  'Select Adjustment Type': 'Select Adjustment Type',
  'Increase': 'Increase',
  'Decrease': 'Decrease',
  'Reference NO': 'Reference NO',
  'Enter Reference Number': 'Enter Reference Number',
  'Previous Stock': 'Previous Stock',
  'Enter Previous Stock': 'Enter Previous Stock',
  'New Quantity': 'New Quantity',
  'Add Stock Transfer': 'Add Stock Transfer',
  'Enter New Quantity': 'Enter New Quantity',
  'Reason': 'Reason',
  'Enter Reason': 'Enter Reason',
  'Stock Adjustment Detail': 'Stock Adjustment Detail',
  'Edit Stock Adjustment': 'Edit Stock Adjustment',
  'Search Stock Transfer':'Search Stock Transfer',
  'Stock Transfer Detail': 'Stock Transfer Detail',
  'Edit Stock Transfer': 'Edit Stock Transfer',
  'Search Warehouse': 'Search Warehouse',
  'Search Sale': 'Search Sale',
  'Sale List Detail': 'Sale List Detail',
  'New Sale': 'New Sale',
  'Payment': 'Payment',
  'Search Role': 'Search Role',
  'Add Role': 'Add Role',
  'Role Name': 'Role Name',
  'Enter Role Name': 'Enter Role Name',
  'Edit Role':'Edit Role',
  'Active Users': 'អ្នកប្រើប្រាស់សកម្ម',
  'Inactive Users': 'Inactive Users',
  'Search User...': 'Search User...',
  'New User': 'New User',
  'Add User': 'Add User',
  'Select User Type': 'Select User Type',
  'Username': 'Username',
  'Enter Username': 'Enter Username',
  'Enter Password': 'Enter Password',
  'Disable User': 'Disable User',
  'Dashboard': 'Dashboard',
  'Manage': 'Manage',
  'Profile': 'Profile',
  'Personal Info Widget': 'Personal Info Widget',
  'Full Name': 'Full Name',
  'Email Address': 'Email Address',
  'Logout': 'Logout',
  'App Preferences': 'App Preferences',
  'Dark Mode': 'Dark Mode',
  'Language': 'Language',
  'Push Notifications': 'Push Notifications',
  'Product Management': 'Product Management',
  'Purchase Management': 'Purchase Management',
  'Supplier Management': 'Supplier Management',
  'View Sales': 'View Sales',
  'Go to Sale': 'Go to Sale',
  'Payments': 'Payments',
  'Role Management': 'Role Management',
  'User Management': 'User Management',
  'Supplier & Customer Management': 'Supplier & Customer Management',
  'Stock Management': 'Stock Management',
  'Sale Management': 'Sale Management',
  'User & Role Management': 'User & Role Management',
  'Choose your preferred language':'Choose your preferred language',
  'User Profile': 'User Profile',
  'ACTIVE': 'ACTIVE',
  'INACTIVE': 'INACTIVE',
  'Account Info': 'Account Info',
  'Role Info': 'Role Info',
  'Updated': 'Updated',
  'System Info': 'System Info',
  'ID':'ID',
  'Edit User': 'Edit User',
  'Password': 'Password',
  'From Warehouse':'From Warehouse',
  'Select From Warehouse':'Select From Warehouse',
  'To Warehouse':'To Warehouse',
  'Select To Warehouse':'Select To Warehouse',
  'Transfer Date':'Transfer Date',
  'Select Transfer Date':'Select Transfer Date',
  'Select Date':'Select Date',
};