const Map<String, String> kmKH = {
  'hello': 'សួស្តី',
  'welcome': 'សូមស្វាគមន៍',
  'Home':'ទំព័រដើម',
  'Quick Action':'សកម្មភាពរហ័ស',
  'Select Language':'ជ្រើសរើសភាសា',
  'Recent Purchase Order':'ការបញ្ជាទិញថ្មីៗ',
  'Recent Sale Order':'ការលក់ថ្មីៗ',
  'View All':'មើលទាំងអស់',
  'Login':'ចូលប្រព័ន្ធ',
  'Enter username': 'បញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
  'Enter password': 'បញ្ចូលពាក្យសម្ងាត់',
  'Good Morning 👋': 'អរុណសួស្តី 👋',
  'Good Afternoon': 'ទិវាសួស្តី',
  'Good Evening': 'សាយណ្ហសួស្តី',
  'Good Night': 'រាត្រីសួស្តី',
  'Welcome Back': 'ស្វាគមន៍ការត្រឡប់មកវិញ',
  'Sale':'ការលក់',
  'Category':'ប្រភេទផលិតផល',
  'Product':'ផលិតផល',
  'Supplier':'អ្នកផ្គត់ផ្គង់',
  'Qty':'ចំនួន',
  'Price':'តម្លៃ',
  'Date':'កាលបរិច្ឆេទ',
  'Purchase':'ការបញ្ជាទិញ',
  'Category Management':'គ្រប់គ្រងប្រភេទផលិតផល',
  'Customer':'អតិថិជន',
  'Audit Logs':'កំណត់ហេតុសវនកម្ម',
  'Stock Adjustment': 'ការកែសម្រួលស្តុក',
  'Stock Transfer': 'ការផ្ទេរស្តុក',
  'Warehouse': 'ឃ្លាំង',
  'Sale List': 'បញ្ជីការលក់',
  'Sale Payment': 'ការទូទាត់ការលក់',
  'Role': 'តួនាទី',
  'User': 'អ្នកប្រើប្រាស់',
  'Product & Category Management': 'ការគ្រប់គ្រងផលិតផល និងប្រភេទ',
  'Search Category':'ស្វែងរកប្រភេទផលិតផល',
  'Add Category':'បន្ថែមប្រភេទផលិតផល',
  'Edit Category':'កែប្រែប្រភេទផលិតផល',
  'Category Name': 'ឈ្មោះប្រភេទផលិតផល',
  'Icon': 'រូបតំណាង',
  'Description':'ពិពណ៌នា',
  'Enter Category Name': 'បញ្ចូលឈ្មោះប្រភេទផលិតផល',
  'Enter Description': 'បញ្ចូលពិពណ៌នាប្រភេទផលិតផល',
  'Enter Icon':'បញ្ចូលរូបតំណាង',
  'Save':'រក្សាទុក',
  'Delete':'លុប',
  'Edit':'កែប្រែ',
  'Search Product':'ស្វែងរកផលិតផល',
  'Add Product':'បញ្ចូលផលិតផល',
  'Pick Image':'ជ្រើសរើសរូបភាព',
  'Enter Category':'បញ្ចូលប្រភេទផលិតផល',
  'Product Name': 'ឈ្មោះផលិតផល',
  'Enter Product Name': 'បញ្ចូលឈ្មោះផលិតផល',
  'Select Category':'ជ្រើសរើសប្រភេទផលិតផល',
  'Select Supplier':'ជ្រើសរើសអ្នកផ្គត់ផ្គង់',
  'Barcode':'បាកូដ',
  'Enter Barcode':'បញ្ចូលបាកូដ',
  'Cost Price':'តម្លៃដើម',
  'Enter Cost Price':'បញ្ចូលតម្លៃដើម',
  'Sale Price': 'តម្លៃលក់',
  'Enter Sale Price': 'បញ្ចូលតម្លៃលក់',
  'Quantity': 'បរិមាណ',
  'Enter Quantity': 'បញ្ចូលបរិមាណ',
  'Unit': 'ឯកតា',
  'Select Unit': 'ជ្រើសរើសឯកតា',
  'Product Detail':'ព័ត៌មានលម្អិតផលិតផល',
  'Edit Product':'កែប្រែផលិតផល',
  'Total Purchases':'ចំនួនការទិញសរុប',
  'Purchases':'ការបញ្ជាទិញ',
  'Search Purchases...':'ស្វែងរកការបញ្ជាទិញ...',
  'Search Suppliers':'ស្វែងរកអ្នកផ្គត់ផ្គង់',
  'Suppliers':'អ្នកផ្គត់ផ្គង់',
  'Add Supplier':'បញ្ចូលអ្នកផ្គត់ផ្គង់',
  'Supplier Name':'ឈ្មោះអ្នកផ្គត់ផ្គង់',
  'Enter Supplier Name':'បញ្ចូលឈ្មោះអ្នកផ្គត់ផ្គង់',
  'Phone Number':'លេខទូរស័ព្ទ',
  'Enter Phone Number':'បញ្ចូលលេខទូរស័ព្ទ',
  'Email':'អ៊ីមែល',
  'Enter Email':'បញ្ចូលអ៊ីមែល',
  'Map': 'ផែនទី',
  'Enter Map': 'បញ្ចូលផែនទី',
  'Address': 'អាសយដ្ឋាន',
  'Enter Address': 'បញ្ចូលអាសយដ្ឋាន',
  'Status': 'ស្ថានភាព',
  'No supplier data found':'មិនមានទិន្នន័យអ្នកផ្គត់ផ្គង់',
  'Supplier Detail':'ព័ត៌មានលម្អិតអ្នកផ្គត់ផ្គង់',
  'Supplier Information': 'ព័ត៌មានអ្នកផ្គត់ផ្គង់',
  'Created': 'បានបង្កើត',
  'Edit Supplier':'កែប្រែអ្នកផ្គត់ផ្គង់',
  'Search Customers by name or ID':'ស្វែងរកអ្នកទិញដោយឈ្មោះឬ ID',
  'Total Customers':'ចំនួនសរុបអតិថិជន',
  'Active Customers':'អតិថិជនសកម្ម',
  'Inactive Customers':'អតិថិជនអសកម្ម',
  'Customer Name':'ឈ្មោះអតិថិជន',
  'Enter Customer Name':'បញ្ចូលឈ្មោះអតិថិជន',
  'Add Customer':'បញ្ចូលអតិថិជន',
  'Edit Customer':'កែប្រែអតិថិជន',
  'Search Stock Adjustment':'ស្វែងរកការកែសម្រួលស្តុក',
  'Select Product':'ជ្រើសរើសផលិតផល',
  'Select Warehouse':'ជ្រើសរើសឃ្លាំងស្តុក',
  'Adjustment Type': 'ប្រភេទការកែសម្រួល',
  'Add Stock Adjustment':'បញ្ចូលការកែសម្រួលស្តុក',
  'Select Adjustment Type': 'ជ្រើសរើសប្រភេទការកែសម្រួល',
  'Increase': 'បន្ថែម',
  'Decrease': 'បន្ថយ',
  'Reference NO': 'លេខយោង',
  'Enter Reference Number': 'បញ្ចូលលេខយោង',
  'Previous Stock': 'ស្តុកមុន',
  'Enter Previous Stock': 'បញ្ចូលស្តុកមុន',
  'New Quantity': 'បរិមាណថ្មី',
  'Enter New Quantity': 'បញ្ចូលបរិមាណថ្មី',
  'Reason': 'មូលហេតុ',
  'Enter Reason': 'បញ្ចូលមូលហេតុ',
  'Stock Adjustment Detail': 'ព័ត៌មានលម្អិតការកែសម្រួលស្តុក',
  'Edit Stock Adjustment': 'កែប្រែការកែសម្រួលស្តុក',
  'Search Stock Transfer':'ស្វែងរកការផ្ទេរស្តុក',
  'Add Stock Transfer': 'បញ្ចូលការផ្ទេរស្តុក',
  'From Warehouse': 'ពីឃ្លាំង',
  'Select From Warehouse': 'ជ្រើសរើសឃ្លាំងដើម',
  'To Warehouse': 'ទៅឃ្លាំង',
  'Select To Warehouse': 'ជ្រើសរើសឃ្លាំងគោលដៅ',
  'Transfer Date': 'កាលបរិច្ឆេទផ្ទេរ',
  'Select Date': 'ជ្រើសរើសកាលបរិច្ឆេទ',
  'Stock Transfer Detail': 'ព័ត៌មានលម្អិតការផ្ទេរស្តុក',
  'Edit Stock Transfer': 'កែប្រែការផ្ទេរស្តុក',
  'Search Warehouse': 'ស្វែងរកឃ្លាំង',
  'Search Sale': 'ស្វែងរកការលក់',
  'Sale List Detail': 'ព័ត៌មានលម្អិតបញ្ជីការលក់',
  'New Sale': 'ការលក់ថ្មី',
  'Payment': 'ការទូទាត់',
  'Search Role': 'ស្វែងរកតួនាទី',
  'Add Role': 'បន្ថែមតួនាទី',
  'Role Name': 'ឈ្មោះតួនាទី',
  'Enter Role Name': 'បញ្ចូលឈ្មោះតួនាទី',
  'Edit Role':'កែប្រែតួនាទី',
  'Active Users': 'អ្នកប្រើប្រាស់សកម្ម',
  'Inactive Users': 'អ្នកប្រើប្រាស់អសកម្ម',
  'Search User...': 'ស្វែងរកអ្នកប្រើប្រាស់...',
  'New User': 'អ្នកប្រើប្រាស់ថ្មី',
  'Add User': 'បន្ថែមអ្នកប្រើប្រាស់',
  'Select User Type': 'ជ្រើសរើសប្រភេទអ្នកប្រើប្រាស់',
  'Username': 'ឈ្មោះអ្នកប្រើប្រាស់',
  'Enter Username': 'បញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
  'Enter Password': 'បញ្ចូលពាក្យសម្ងាត់',
  'Disable User': 'បិទអ្នកប្រើប្រាស់',
  'Dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'Manage': 'គ្រប់គ្រង',
  'Profile': 'ប្រវត្តិរូប',
  'Personal Info Widget': 'ព័ត៌មានផ្ទាល់ខ្លួន',
  'Full Name': 'ឈ្មោះពេញ',
  'Email Address': 'អាសយដ្ឋានអ៊ីមែល',
  'Logout': 'ចាកចេញ',
  'App Preferences': 'ការកំណត់កម្មវិធី',
  'Dark Mode': 'ផ្ទៃងងឹត',
  'Light Mode': 'ផ្ទៃភ្លឺ',
  'Language': 'ភាសា',
  'Push Notifications': 'ការជូនដំណឹង',
  'Product Management': 'គ្រប់គ្រងផលិតផល',
  'Purchase Management': 'ការគ្រប់គ្រងការទិញ',
  'Supplier Management': 'ការគ្រប់គ្រងអ្នកផ្គត់ផ្គង់',
  'View Sales': 'មើលការលក់',
  'Go to Sale': 'ទៅកាន់ការលក់',
  'Payments': 'ការទូទាត់',
  'Role Management': 'ការគ្រប់គ្រងតួនាទី',
  'User Management': 'ការគ្រប់គ្រងអ្នកប្រើប្រាស់',
  'Supplier & Customer Management': 'ការគ្រប់គ្រងអ្នកផ្គត់ផ្គង់ និងអតិថិជន',
  'Stock Management': 'ការគ្រប់គ្រងស្តុក',
  'Sale Management': 'ការគ្រប់គ្រងការលក់',
  'User & Role Management': 'ការគ្រប់គ្រងអ្នកប្រើប្រាស់ និងតួនាទី',
  'Choose your preferred language':'ជ្រើសរើសភាសា​របស់អ្នក',
  'User Profile': 'ព័ត៌មានអ្នកប្រើប្រាស់',
  'ACTIVE': 'សកម្ម',
  'INACTIVE': 'មិនសកម្ម',
  'Account Info': 'ព័ត៌មានគណនី',
  'Role Info': 'ព័ត៌មានតួនាទី',
  'Updated': 'បានធ្វើបច្ចុប្បន្នភាព',
  'System Info': 'ព័ត៌មានប្រព័ន្ធ',
  'ID':'លេខអត្តសញ្ញាណ',
  'Edit User': 'កែប្រែអ្នកប្រើប្រាស់',
  'Password': 'ពាក្យសម្ងាត់',
  

};